### ISSUE TITLE
prometheus sink fails when using two rollups with different dimension but the same metric

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#14]
### One rollup: OK 

``` 
dpajin@dpajin-t14:~/Documents/kentik/uber$ curl -i http://127.0.0.1:8084/metrics 
HTTP/1.1 200 OK 
Content-Type: text/plain; version=0.0.4; charset=utf-8 
Date: Mon, 28 Jun 2021 08:40:20 GMT 
Transfer-Encoding: chunked 
  
# HELP KFlow:in_bytes  
# TYPE KFlow:in_bytes counter 
KFlow:in_bytes{protocol="ICMP",src_addr="13.49.70.51"} 44 
KFlow:in_bytes{protocol="ICMP",src_addr="13.71.22.26"} 88 
KFlow:in_bytes{protocol="ICMP",src_addr="15.161.94.26"} 44 
KFlow:in_bytes{protocol="ICMP",src_addr="164.90.187.204"} 88 
KFlow:in_bytes{protocol="ICMP",src_addr="172.104.224.193"} 44 
KFlow:in_bytes{protocol="ICMP",src_addr="193.177.129.11"} 176 
KFlow:in_bytes{protocol="ICMP",src_addr="20.194.173.78"} 44 
KFlow:in_bytes{protocol="ICMP",src_addr="20.90.85.170"} 44 
KFlow:in_bytes{protocol="ICMP",src_addr="20.94.208.125"} 44 
KFlow:in_bytes{protocol="ICMP",src_addr="212.80.207.250"} 72 
KFlow:in_bytes{protocol="ICMP",src_addr="34.87.71.235"} 84 
``` 

 
### Two rollups with different dimension but the same metric fails
 
It seems that the problem is with using the series for the rollup. According to the convention applied the name of the series would be the same "Kflow:in_bytes", but with the different labels that those already used and that is the reason why it fails.  
I would suggest to use user-defined rollup name for series instead of current one: so for example "Kflow:src_addr_grouping" or just "src_addr_grouping".  
Then it is up to user to ensure that the rollup name is unique. 

```
command: -file_on -format prometheus -sinks prometheus -prom_listen=:8084 -file_out /ktranslate/logs -listen 0.0.0.0:13000 -rollups sum,src_addr_grouping,in_bytes,src_addr,protocol -rollups sum,dst_addr_grouping,in_bytes,dst_addr -rollup_key_join "|" -rollup_interval 30 -rollup_top_k 10 
 
 
dpajin@dpajin-t14:~/Documents/kentik/uber$ docker-compose logs ktranslate 
Attaching to ktranslate 
ktranslate    | 2021-06-28T08:35:10.442 ktranslate [Info] ktranslate version dirty-6878b373dab54217407d09e830dae645dd784272 starting 
ktranslate    | 2021-06-28T08:35:10.442 ktranslate [Info] ktranslate olly: disabled 
ktranslate    | 2021-06-28T08:35:10.442 ktranslate [Info] ktranslate Setting metrics: syslog 
ktranslate    | 2021-06-28T08:35:10.442 ktranslate [Error] ktranslate Could not start syslog metrics: Unix syslog delivery error 
ktranslate    | 2021-06-28T08:35:10.448 ktranslate [Info] KTranslate Turning on 1 processing threads 
ktranslate    | 2021-06-28T08:35:10.448 ktranslate [Info] sumRollup New Rollup: KFlow:in_bytes:src_addr:protocol -> Name: src_addr_grouping, Method: sum, Adjust Sample Rate: false, Metric: [in_bytes], Dimensions: [src_addr protocol], value of 0.000000 
ktranslate    | 2021-06-28T08:35:10.448 ktranslate [Info] sumRollup New Rollup: KFlow:in_bytes:dst_addr -> Name: dst_addr_grouping, Method: sum, Adjust Sample Rate: false, Metric: [in_bytes], Dimensions: [dst_addr], value of 0.000000 
ktranslate    | 2021-06-28T08:35:10.544 ktranslate [Info] KTranslate Loaded Code2city from /etc/code2city.mdb 
ktranslate    | 2021-06-28T08:35:10.601 ktranslate [Info] KTranslate Loaded Code2Region from /etc/code2region.mdb 
ktranslate    | 2021-06-28T08:35:10.602 ktranslate [Info] KTranslate Loaded 128 custom mappings 
ktranslate    | 2021-06-28T08:35:10.604 ktranslate [Info] KTranslate Loaded 12 udr and 23 subtype mappings with 347 udrs total 
ktranslate    | 2021-06-28T08:35:11.777 ktranslate [Info] KTranslate Loaded 978787 asn cidrs with 103246 names 
ktranslate    | 2021-06-28T08:35:11.777 ktranslate [Info] KTranslate Using sink prometheus 
ktranslate    | 2021-06-28T08:35:11.777 ktranslate [Info] KTranslate Version dirty-6878b373dab54217407d09e830dae645dd784272; Build un-dated build 
ktranslate    | 2021-06-28T08:35:11.777 ktranslate [Info] KTranslate Running 
ktranslate    | 2021-06-28T08:35:11.777 ktranslate [Info] baseserver.metaserver Listening on [::]:8083 
ktranslate    | 2021-06-28T08:35:11.814 ktranslate [Info] promSink Prometheus listening on :8084 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate API server running 1 devices 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate Loaded 1 Kentik devices via local file 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate System running with format prometheus, compression none, max flows: 10000, sample rate 1:1 after 1 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate sendToSinks base Online 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate sendToSink 0 Online 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate do sendToKTranslate Starting 
ktranslate    | 2021-06-28T08:35:11.815 ktranslate [Info] KTranslate monitorInput 0 Starting 
ktranslate    | 2021-06-28T08:35:11.816 ktranslate [Info] KTranslate Setting up HTTP system on 0.0.0.0:13000/chf 
ktranslate    | panic: a previously registered descriptor with the same fully-qualified name as Desc{fqName: "KFlow:in_bytes", help: "", constLabels: {}, variableLabels: [dst_addr]} has different label names or a different help string 
ktranslate    |  
ktranslate    | goroutine 76 [running]: 
ktranslate    | github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000096960, 0xc00301dde0, 0x1, 0x1) 
ktranslate    | /home/pye/dev/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:403 +0xb7 
ktranslate    | github.com/prometheus/client_golang/prometheus.MustRegister(...) 
ktranslate    | /home/pye/dev/go/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:178 
ktranslate    | github.com/kentik/ktranslate/pkg/formats/prom.(*PromFormat).Rollup(0xc0015ea000, 0xc00244e800, 0x61, 0x61, 0x0, 0x0, 0x0) 
ktranslate    | /home/pye/dev/go/src/github.com/kentik/ktranslate/pkg/formats/prom/prom.go:161 +0x465 
ktranslate    | github.com/kentik/ktranslate/pkg/cat.(*KTranslate).sendToSinks(0xc0002f14a0, 0x192a848, 0xc001f4ab40, 0x0, 0x0) 
ktranslate    | /home/pye/dev/go/src/github.com/kentik/ktranslate/pkg/cat/kkc.go:584 +0x402 
ktranslate    | github.com/kentik/ktranslate/pkg/cat.(*KTranslate).Run(0xc0002f14a0, 0x192a848, 0xc001f4ab40, 0x0, 0x0) 
ktranslate    | /home/pye/dev/go/src/github.com/kentik/ktranslate/pkg/cat/kkc.go:969 +0x710 
ktranslate    | github.com/kentik/ktranslate/pkg/eggs/baseserver.(*BaseServer).Run.func1(0x19301d8, 0xc0002f14a0, 0xc000098d80, 0x192a848, 0xc001f4ab40) 
ktranslate    | /home/pye/dev/go/src/github.com/kentik/ktranslate/pkg/eggs/baseserver/baseserver.go:253 +0x70 
ktranslate    | created by github.com/kentik/ktranslate/pkg/eggs/baseserver.(*BaseServer).Run 
ktranslate    | /home/pye/dev/go/src/github.com/kentik/ktranslate/pkg/eggs/baseserver/baseserver.go:251 +0x318 
```

**Comment by i3149** [comment]
Can you verify this is working now?

**Comment by dpajin-kentik** [comment]
Yes, this works, closing the ticket

```
curl -i http://127.0.0.1:8084/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Thu, 15 Jul 2021 16:15:37 GMT
Transfer-Encoding: chunked

# HELP dst_addr_grouping 
# TYPE dst_addr_grouping counter
dst_addr_grouping{dst_addr="193.177.128.3",protocol="TCP"} 21611
dst_addr_grouping{dst_addr="193.177.129.11",protocol="TCP"} 59436
dst_addr_grouping{dst_addr="193.177.129.21",protocol="TCP"} 409471
dst_addr_grouping{dst_addr="193.177.129.21",protocol="UDP"} 1.115955e+06
dst_addr_grouping{dst_addr="193.177.129.22",protocol="TCP"} 444357
dst_addr_grouping{dst_addr="193.177.129.22",protocol="UDP"} 726516
dst_addr_grouping{dst_addr="193.177.129.23",protocol="TCP"} 1.875198e+06
dst_addr_grouping{dst_addr="193.177.129.24",protocol="TCP"} 4.36098e+06
dst_addr_grouping{dst_addr="193.177.129.24",protocol="UDP"} 167771
dst_addr_grouping{dst_addr="193.177.129.25",protocol="TCP"} 2.662454e+06
dst_addr_grouping{dst_addr="193.177.129.25",protocol="UDP"} 333920
dst_addr_grouping{dst_addr="193.177.129.26",protocol="TCP"} 2.853639e+06
dst_addr_grouping{dst_addr="193.177.129.26",protocol="UDP"} 1.5338645e+07
dst_addr_grouping{dst_addr="193.177.129.27",protocol="TCP"} 1.875087e+06
dst_addr_grouping{dst_addr="193.177.129.27",protocol="UDP"} 1.3900744e+07
dst_addr_grouping{dst_addr="193.177.129.28",protocol="TCP"} 492178
dst_addr_grouping{dst_addr="193.177.129.28",protocol="UDP"} 1.184648e+06
dst_addr_grouping{dst_addr="193.177.129.29",protocol="TCP"} 3.913593e+06
dst_addr_grouping{dst_addr="193.177.129.29",protocol="UDP"} 4.8776112e+07
dst_addr_grouping{dst_addr="193.177.129.30",protocol="TCP"} 121514
dst_addr_grouping{dst_addr="193.177.129.30",protocol="UDP"} 229220
dst_addr_grouping{dst_addr="193.177.129.61",protocol="TCP"} 282633
dst_addr_grouping{dst_addr="194.37.251.128",protocol="TCP"} 7990
dst_addr_grouping{dst_addr="213.246.151.2",protocol="TCP"} 6381
dst_addr_grouping{dst_addr="37.10.26.33",protocol="TCP"} 13148
dst_addr_grouping{dst_addr="79.99.199.251",protocol="TCP"} 20215

...

# HELP src_addr_grouping 
# TYPE src_addr_grouping counter
src_addr_grouping{protocol="TCP",src_addr="188.172.144.246"} 724825
src_addr_grouping{protocol="TCP",src_addr="192.114.75.55"} 4.238432e+06
src_addr_grouping{protocol="TCP",src_addr="192.114.75.56"} 4.492655e+06
src_addr_grouping{protocol="TCP",src_addr="192.114.75.69"} 2.180389e+06
src_addr_grouping{protocol="TCP",src_addr="193.1.248.200"} 679794
src_addr_grouping{protocol="TCP",src_addr="212.60.32.159"} 800911
src_addr_grouping{protocol="UDP",src_addr="102.165.8.2"} 4.583978e+06
src_addr_grouping{protocol="UDP",src_addr="105.16.0.164"} 1.444587e+06
src_addr_grouping{protocol="UDP",src_addr="141.98.88.90"} 734574
src_addr_grouping{protocol="UDP",src_addr="212.25.114.8"} 1.871988e+06
src_addr_grouping{protocol="UDP",src_addr="212.25.114.9"} 2.16926e+06
src_addr_grouping{protocol="UDP",src_addr="212.25.68.15"} 1.679471e+06
src_addr_grouping{protocol="UDP",src_addr="212.25.68.16"} 2.269041e+06
src_addr_grouping{protocol="UDP",src_addr="89.21.210.84"} 9.997468e+06
src_addr_grouping{protocol="UDP",src_addr="89.21.210.85"} 1.6538636e+07
src_addr_grouping{protocol="UDP",src_addr="89.21.210.86"} 1.0048888e+07
src_addr_grouping{protocol="UDP",src_addr="94.101.60.146"} 6.363964e+06
src_addr_grouping{protocol="UDP",src_addr="94.101.60.147"} 5.0225e+06

```
