### ISSUE TITLE
Use of snmp_out_file results in panic

### ISSUE THREAD

**Issue by halfinhalfout** [kentik/ktranslate#772]
I'm trying to use the `snmp_out_file` option provided by
https://github.com/kentik/ktranslate/issues/135

When I specify a file that doesn't exist, I see an error like:
```
[Error] KTranslate Discovery SNMP Error: There was an error when writing the /etc/ktranslate/snmp-out.yaml SNMP configuration file: stat /etc/ktranslate/snmp-out.yaml: no such file or directory.
```

When the file exists, is empty, and the user running ktranslate can write to the file, this is what I see in the log:
```
[Info] KTranslate Writing snmp config file to /etc/ktranslate/snmp-out.yaml.
...
Nov 01 21:43:32 ip-172-20-222-4 ktranslate[13953]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 01 21:43:32 ip-172-20-222-4 ktranslate[13953]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1908afb]
Nov 01 21:43:32 ip-172-20-222-4 systemd[1]: ktranslate.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

I'm using ktranslate version **2.2.29** on Ubuntu 24.04.

FWIW, when I downgraded to ktranslate version **2.2.28**, the error is different:
```
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: 2024-11-01T22:00:15.753 ktranslate/dkw-snmpwalker [Info] KTranslate Checked 1 ips in 77.443645ms (from start: 88.319361ms)
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1786afb]
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: goroutine 85 [running]:
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: github.com/kentik/ktranslate/pkg/inputs/snmp.addDevices({0x2a9a350, 0xc0000a53b0}, 0xc00467e630, {0x7ffe8b825cdf, 0x1d}, 0xc000b4d3c0, 0xa0?, {0x2aa5a88?, 0xc000b68ec0?}, 0x68c61714000)
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]:         /__w/ktranslate/ktranslate/pkg/inputs/snmp/disco.go:384 +0x83b
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: github.com/kentik/ktranslate/pkg/inputs/snmp.Discover({0x2a9a350, 0xc0000a53b0}, {0x2aa5a88, 0xc000b68ec0}, 0x68c61714000?, 0xc000be1900, 0xc00115a840?, {0x0, 0x0})
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]:         /__w/ktranslate/ktranslate/pkg/inputs/snmp/disco.go:139 +0xeac
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: github.com/kentik/ktranslate/pkg/inputs/snmp.RunDiscoOnTimer.func1()
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]:         /__w/ktranslate/ktranslate/pkg/inputs/snmp/disco.go:158 +0x56
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: github.com/kentik/ktranslate/pkg/inputs/snmp.RunDiscoOnTimer({0x2a9a350?, 0xc0000a53b0}, 0x0?, {0x2aa5a88?, 0xc000b68ec0}, 0x78, 0x0?, 0x0?, 0x0?, {0x0, ...})
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]:         /__w/ktranslate/ktranslate/pkg/inputs/snmp/disco.go:172 +0x122
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]: created by github.com/kentik/ktranslate/pkg/inputs/snmp.wrapSnmpPolling in goroutine 74
Nov 01 22:00:15 ip-172-20-222-4 ktranslate[14611]:         /__w/ktranslate/ktranslate/pkg/inputs/snmp/snmp_unix.go:37 +0x3a8
Nov 01 22:00:15 ip-172-20-222-4 systemd[1]: ktranslate.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by i3149** [comment]
Will take a look, thanks for the nice stack trace!
